services:
  postgres:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  backend:
    volumes:
      - ./apps/backend/app:/app/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
      - /app/.next
    command: ["sh", "-c", "npm install && npm run dev"]
    ports:
      - "3000:3000"

  simulator:
    volumes:
      - ./apps/simulator/simulator:/app/simulator
      - ./apps/simulator/config.json:/app/config.json
