-- Demo card registry seed — insert 3 test operator cards for local development.
--
-- IMPORTANT: uid_hash values here are SHA-256 of fictional test UIDs.
-- Replace with real hashes (sha256sum of actual card UIDs) before production.
--
-- Rows to insert into the cards table:
--
--  | operator_name    | role        | assigned_locomotive_id | uid_hash (placeholder) |
--  |------------------|-------------|------------------------|------------------------|
--  | Machinist Demo 1 | Machinist   | LOC-001                | <sha256 of TEST-UID-1> |
--  | Dispatcher Demo  | Dispatcher  | NULL                   | <sha256 of TEST-UID-2> |
--  | Admin Demo       | Admin       | NULL                   | <sha256 of TEST-UID-3> |
--
-- For local testing without a physical reader, the /login page provides
-- a manual UID input that sends directly to POST /api/auth/card.
